/* Political-poetic commentary layer.
   Adds event-specific historical/civilizational texture without replacing the concrete event writing.
   The player's timeline is always treated as the only history that exists. */

const OATR_POLITICAL_CODA = {
1:()=>`There is something almost medieval about the scene: industrial workers, carrying holy images through a modern capital, appealing over the heads of bureaucrats to a sovereign they have never met. Russia has built factories without fully deciding whether the men inside them are subjects, citizens, children of the Tsar, or a dangerous crowd. By nightfall the answer may be written in snow.`,
2:()=>`The empire has discovered the peculiar intimacy of defeat. Mukden is thousands of miles away, yet every lost train and casualty list arrives in Petersburg as an argument about the competence of the dynasty itself. A great power can lose a battle abroad. An autocracy risks losing the explanation for why it should be obeyed at home.`,
3:()=>`The Kremlin is supposed to be the stone heart of continuity: walls, bells, relics, dynasties. Now servants are gathering a Romanov from the courtyard with blankets. The Empire continues issuing documents because documents are what states do when blood has entered sacred space.`,
4:ctx=>ctx.flag('earlyPeace1905')?`The fleet comes home intact enough to preserve pride, careers, habits and excuses. Russia has escaped catastrophe and therefore escaped some of the lessons catastrophe teaches brutally. A ship saved from battle can carry an institution's defects safely back into harbor.`:`The humiliation is total enough to feel theological. A fleet consecrated with icons and funded by a state that calls itself a great power has been turned into burning silhouettes by a country court society still remembers as an upstart. Modernity has answered the imperial myth with range-finders, wireless signals and shells.`,
5:()=>`The red flag above a battleship frightens the court because it collapses categories the regime depends upon. Sailor and revolutionary, servant and mutineer, weapon and constituency become the same object. The state built the ship; now the ship has acquired politics.`,
6:()=>`The proposed Duma is a doorway designed by men who hope nobody will actually walk through it. Yet once elections are announced, even a decorative institution becomes a place where millions may imagine themselves represented. Russia is learning that a fiction shared by enough people becomes architecture.`,
7:()=>`Portsmouth ends the shooting without resolving what the war meant. Peace returns the soldiers, debts and embarrassment to the same country that sent them east. An empire may sign away territory more easily than it signs away the story it told itself about why the territory was worth taking.`,
8:()=>`For generations the state imagined power moving downward: decree, governor, police, factory, worker. The strike reveals a second circuit running upward. The worker stops. The railway stops. The telegram stops. Suddenly the autocrat discovers that obedience was never only fear; it was also millions of ordinary people continuing to do their jobs.`,
9:()=>`The manifesto is written in the language of concessions, but history may later read it as a transfer of metaphysics. If law can bind the sovereign even once, then the sovereign is no longer the only source from which political reality flows. That possibility terrifies men who have spent their lives calling personal authority sacred.`,
10:()=>`The Black Hundreds offer the monarchy a seductive bargain: let private hatred perform public order. It is cheap, deniable and emotionally satisfying. It also teaches armed men that loyalty gives them jurisdiction over who counts as Russian. The throne may someday discover it has created electors with clubs.`,
11:()=>`Kronstadt is close enough to Petersburg that the guns can almost be imagined from the palace. The regime keeps meeting the same impossible fact in new uniforms: discipline cannot indefinitely compensate for institutions that humiliate the disciplined.`,
12:()=>`Presnya can be reduced with artillery. That is the easy part. The difficult part is what happens afterward, when a worker who never held a rifle learns that the government considers his street a target grid. Empires survive many rebellions. Memories have longer supply lines.`,
13:()=>`The Fundamental Laws ask the oldest Russian question in legal prose: is the state something the Tsar possesses, or something the Tsar inhabits? Every ambiguous clause postpones the answer, but postponement is not neutrality. It merely allows custom, crisis and whoever acts first to answer later.`,
14:()=>`The Tauride Palace is loud, vain, theatrical and alive. That is exactly why the court dislikes it. Autocracy is aesthetically clean: one will, one crown, one vertical line. Politics is ugly because society is ugly when allowed into the room.`,
15:()=>`Dissolution is lawful. That may make it more dangerous, not less. A regime can teach people that legality is simply the method by which power arranges its own victory, and then be surprised when legality ceases to command respect.`,
16:()=>`The bomb at Stolypin's dacha makes the argument for repression with bodies. It also makes the argument for reform with the same bodies. Terrorism wants the state to choose the answer that proves the terrorist's description of the state correct.`,
17:()=>`The peasant question is where every Russian abstraction eventually meets mud. Autocracy, socialism, liberalism and holy tradition all become less elegant when measured in strips of land, inheritance disputes, horse teams and whether a family can borrow without selling its future.`,
18:()=>`The Second Duma is intolerable partly because it is representative of a country the court does not particularly like seeing represented. The temptation is to improve the nation by improving the electorate. Russia will perform this operation many times under many names.`,
19:()=>`The Third Duma works because the arithmetic has been made friendlier. That creates a subtler danger than open crisis: institutions can become decorative precisely when they behave well enough that nobody fears them. A parliament domesticated into irrelevance is still a lesson, just not the intended one.`,
20:()=>`The budget is one of the few documents in the empire incapable of believing myths. It does not care that a battleship is sacred, that a railway is civilizing, that a noble exemption is traditional or that a school is patriotic. It merely adds the numbers and waits for politics to lie about them.`,
21:()=>`Surveyors now do what manifestos cannot: they draw borders around property and make them enforceable. The revolutionaries promise land in speeches; Stolypin sends men with chains, maps and loan forms. One of these methods is much less romantic, which may be why it is dangerous to the other.`,
22:()=>`Twenty years is not really a request for time. It is a request that the state stop sabotaging itself long enough for consequences to accumulate. Russia has often possessed clever reformers. Its rarer resource is the willingness to leave one alive, in office, and unbetrayed by the man who appointed him.`,
23:()=>`Finland is inconvenient because it remembers treaties, constitutions and administrative habits older than the current argument. Petersburg prefers loyalty to be emotional and law to be flexible. Helsingfors has the irritating habit of bringing paper.`,
24:()=>`Bosnia exposes the weakness beneath Pan-Slavic grandeur. Russia wishes to be protector of the Slavs, guardian of Orthodoxy, European great power and recovering patient at the same time. Vienna has noticed that these roles do not always share an army.`,
25:()=>`Serbia looks small on the map and enormous in Russian imagination. That mismatch is the danger. Prestige allows a minor ally to occupy the emotional space of a vital province, while diplomats continue pretending guarantees are made of words rather than future corpses.`,
26:()=>`The reform memorandum is an indictment written in tables. It says courage was abundant and competence rationed; that patronage survived longer than ammunition; that men died because the institution preferred familiar names to unfamiliar methods. The Guard calls this an insult because statistics are notoriously disrespectful of ancestry.`,
27:()=>`The Church has spent two centuries protected so thoroughly that protection resembles custody. A faith that claims eternity receives instructions from a lay official with office hours. Freeing it may strengthen Orthodoxy and weaken autocracy at once, which is precisely why the question has waited so long.`,
28:()=>`Baku is the empire in miniature and on fire: oil, capital, empire, ethnicity, labor, police, revolution. Everyone is indispensable to production and suspicious of everyone else. The wells keep pumping black wealth from the earth while the city asks who is permitted to own the future above it.`,
29:()=>`Language policy tempts bureaucrats because alphabets appear easier to regulate than loyalties. Yet every banned book and corrected schoolmaster tells a child that speech is political. The state can manufacture nationalists simply by insisting they do not exist.`,
30:()=>`The ministries are vertical because verticality resembles obedience. Their files reveal the cost: everyone can report upward, nobody can decide sideways. The Tsar becomes the point where railway gauges, school budgets, police jurisdictions and fertilizer policy all aspire to meet. Personal rule acquires a stationery problem.`,
31:()=>`The western zemstvo dispute takes the Russian obsession with unity and gives it ballot weights. Every nationality fears becoming a minority inside someone else's definition of fairness. The imperial center responds by attempting to design a local institution whose outcome is known before anyone votes.`,
32:()=>`The secret at the center of the dynasty is not political at all. It is a little boy whose blood will not clot. Around that fact forms an invisible constitution: Alexandra's terror, Nicholas's silence, doctors' helplessness, Rasputin's access. Russia sees the effects and is denied the cause, so naturally it invents demons.`,
33:()=>`Stolypin has reached the characteristic Russian danger point: he is powerful enough to have enemies and not powerful enough to ignore them. His program asks the autocracy to use its strength to build institutions that will eventually make autocratic intervention less necessary. Courtiers understand the paradox and hate him for resolving it in the wrong direction.`,
34:()=>`Bogrov belongs to both the underground and the police files, which in this period is less contradictory than it should be. The security state has stared into conspiracy for so long that some of its agents no longer know whether they are observing history or helping it happen.`,
35:()=>`The bullet in Kiev asks whether reform in Russia was a system or merely a man standing in a doorway. If the work dies with Stolypin, then his enemies were correct in the ugliest possible sense: the empire did not possess institutions, only personalities temporarily strong enough to impersonate them.`,
36:()=>`Prosperity softens the sound of structural failure. Factories open, bond prices rise, restaurants fill, and the unanswered constitutional question becomes easier to postpone because nothing is visibly burning. History is most dangerous when it begins to look reasonable.`,
37:()=>`Persia cannot threaten Russia, which is why the choice matters. Great powers reveal their character most clearly when nobody can make them behave. The language of civilization sounds different from the village watching foreign soldiers collect customs revenue.`,
38:()=>`The empire is calm enough that the palace can mistake calm for vindication. This is how systems become superstitious about survival: every year without catastrophe is interpreted as proof that the causes of catastrophe were imaginary. Beneath the polished floors, the old arguments remain exactly where they were left.`,
39:()=>`Lena is far away until the telegram arrives. Then distance collapses. Industrial Russia has become connected enough that a shooting in Siberia can become a sentence repeated in Petersburg within days. The state modernized communications faster than it modernized the instincts of the men using rifles.`,
40:()=>`Rasputin scandal is politically lethal because it offers a story simpler than the truth. The truth is hemophilia, secrecy, desperation, coincidence, faith and a frightened mother. The story is that Russia is ruled from a bedroom by a debauched peasant sorcerer. History usually prefers the story.`,
41:()=>`Rasputin's warning about war is infuriating because the ridiculous man may be right about the largest question in Europe. A regime obsessed with respectable advice may someday discover that its most vulgar prophet understood the abyss better than its general staffs.`,
42:()=>`The Balkan states have learned the lesson Russia hoped to teach them and not the one Russia intended: nationalism mobilizes armies. Once small nations discover they can make history themselves, patronage becomes less like command and more like responsibility for somebody else's appetite.`,
43:()=>`Mobilization planning is where sovereignty begins to acquire machinery. A Tsar may possess unlimited constitutional authority and still discover that a printed plan, once distributed through thousands of offices, has more practical momentum than a human decision made at midnight.`,
44:()=>`Constantinople is geography infected by theology. Every map of the Straits eventually becomes an icon, every icon eventually becomes a naval estimate. The danger is not wanting the city. The danger is wanting it in several different languages at once and pretending they are the same desire.`,
45:()=>`Three centuries of Romanov rule are presented as one unbroken line because jubilees are not designed to show cracks. Yet the crowds contain peasants freed within living memory, workers born from industrialization, deputies elected to a Duma and children who will grow old in a century no Romanov courtier understands. Continuity is real. So is time.`,
46:()=>`The liturgy outlives the ministry that arranged the procession. That fact should comfort the dynasty and frighten it. Orthodoxy may be one of the few institutions in Russia capable of surviving the state; the state has spent two centuries behaving as if the reverse were true.`,
47:()=>`Azef is not merely scandal. He is a philosophical problem wearing spectacles. If the police need conspiracy to justify the police, and informants need conspiracy to remain valuable, then the state can begin farming the danger it claims to harvest.`,
48:()=>`Poland is the empire's memory of a country that refuses to become only a province. Every attempt to erase that memory gives it new ceremonial importance. The Romanovs may yet discover that sovereignty shared by law can be stronger than sovereignty defended by insisting the other nation is imaginary.`,
49:()=>`Russia wanted Slavic solidarity and received Slavic foreign policy. Serbia and Bulgaria have interests, humiliations, newspapers, officers and dead to avenge. Brotherhood is a beautiful word until brothers divide the inheritance.`,
50:()=>`The Putilov worker of 1914 is not the worker of 1905. He reads more, organizes better and knows that industry has made him necessary. The empire has succeeded in creating a modern proletariat and now seems offended that the proletariat noticed.`,
51:()=>`Cabinet government sounds technical until one remembers what it replaces: the Tsar as the living junction box of the empire. Delegation is difficult for Nicholas not because he loves paperwork, but because every independent institution feels faintly like a theological subtraction.`,
52:()=>`The boy bleeds; the empire does not know; therefore the empire invents an occult constitution. It is one of the cruelest mechanisms in the reign. Nicholas protects his son's privacy and, by doing so, leaves the state defenseless against explanations far worse than the truth.`,
53:()=>`The alliance with France has entered the geometry of deployment. What began as diplomacy now exists in railheads, shell stocks and promises about which army will move first. Treaties become most real at the point where nobody can remember which politician originally signed them.`,
54:()=>`Russia stands between Parisian credit and German kinship, between strategic plans and dynastic letters. The old Europe still speaks as though cousins, monarchs and personal honor can soften blocs. The new Europe has already translated affection into mobilization assumptions.`,
55:()=>`This is the last winter in which every terrible future is still hypothetical. The restaurants are open. The factories are producing. Children skate. Ministers argue about appointments. Europe is filled with people who will later remember 1914 as a door they did not know they were standing beside.`,
56:()=>`Sarajevo is a murder before it is a system. That will not last. Within days every grievance accumulated since 1878 begins climbing onto the corpse: Serbia, Bosnia, Austria, Russia, Germany, prestige, alliances, nationalism. A dead archduke becomes a hook sturdy enough to hang a continent from.`,
57:()=>`The blank cheque is one of those diplomatic phrases that sounds metaphorical until men begin cashing it with mobilization orders. Berlin intends confidence to restrain Russia. Vienna hears permission. The same sentence has already become two policies.`,
58:()=>`Belgrade is asking for a promise because promises alter behavior before they are ever redeemed. If Serbia believes Russia must intervene, its room for compromise expands emotionally while shrinking diplomatically. Guarantees are not only commitments to allies; they are information given to allies about how reckless they may safely become.`,
59:()=>`The ultimatum's cruelty is bureaucratic. It arrives typed, numbered and timed. No cavalry charge, no declaration, merely clauses written so that sovereignty itself becomes the disputed object. Europe approaches apocalypse through punctuation.`,
60:()=>`The Serbian reply is nearly conciliatory enough to expose the purpose of the ultimatum, which is why it may not matter. Diplomacy can reveal that a war is unnecessary and still fail to prevent it. Knowledge is not power when the governments involved have already begun needing the opposite conclusion.`,
61:()=>`Belgrade is shelled and the crisis acquires smoke. From here every capital can point to an action already taken and call its own next action a response. The chain becomes morally convenient because each link can insist it was forged by somebody else.`,
62:()=>`Nicky and Willy write like relatives trying to rescue a world that no longer operates at the scale of relatives. Their telegrams cross institutions staffed by men whose careers depend on plans prepared years earlier. Personal monarchy reaches its most tragic form: two emperors possessing immense power and diminishing control.`,
63:()=>`The gray zone is where peace begins dying without ceremony. No declaration has been made, yet commerce is displaced, reservists move and railway priorities change. The state insists it has not crossed the line because nobody can agree where the line is.`,
64:()=>`The red forms are banal objects. That is their horror. Europe will not be destroyed by a demon opening a gate; it may be destroyed by clerks correctly filling boxes designed by competent men in peacetime.`,
65:()=>`The palace becomes a chamber of competing prophecies: Alexandra says firmness, Rasputin says blood, Sazonov says credibility, generals say readiness. Nicholas has always disliked conflict between people he trusts. Now the habit of soothing disagreement meets a problem that can no longer be soothed.`,
66:()=>`The counterorder is the entire reign compressed into an afternoon. Nicholas decides, doubts, reverses, is warned that reversal has costs, and therefore begins to experience his own authority as coercion from below. The sovereign is free to command until command becomes inconvenient to the machinery built in his name.`,
67:()=>`The German ultimatum offers the final narcotic of every great-power crisis: the chance to experience one's own fear as principle. Berlin calls survival sovereignty. Petersburg calls refusal sovereignty. Two empires discover that dignity is easier to defend than peace because dignity requires no timetable for retreat.`,
68:()=>`Paper burns at the embassy while newspapers invent the first draft of memory outside. Before the armies meet, governments begin fighting over who will be remembered as aggressor. The dead have not yet accumulated, but their explanation is already under construction.`,
69:()=>`There is still an exit, but it has become ugly. That is the test. Peace at the beginning of a crisis is prudence; peace at the end may require humiliation, mistrust and the deliberate sacrifice of positions men spent years calling vital. States often prefer catastrophe to discovering that their vital interests were negotiable.`,
70:ctx=>ctx.flag('eschaton')?`The last political distinction is disappearing: peace and war, command and obedience, prophecy and paperwork. Somewhere beneath the palace the Empire continues to function. That may be the worst thing about it.`:`The final decision is not whether Russia is brave. Every option can be called brave by the people who prefer it. The question is whether nine years of government have produced a state capable of distinguishing sacrifice from necessity before necessity becomes a god.`
};

const OATR_ADVISOR_CODA = {
1:'A monarch can survive being feared. It is harder to survive being personally mourned by people who came carrying your portrait.',
2:'If you want time, buy it deliberately. History charges more when it sells under fire.',
3:'No policy follows cleanly from a coffin. Men who claim otherwise usually wanted the policy before the funeral.',
4:'Do not rebuild the symbol and leave untouched the institution that failed beneath it.',
5:'Make obedience worth distinguishing from submission. Otherwise the next mutiny will recruit from grievance before ideology.',
6:'If representation is to exist, let it represent something besides the limits of your patience.',
7:'A peace treaty can end a war. It cannot end the habit of lying about why the war was fought.',
8:'Your state has learned that society can withdraw labor. Learn faster than the revolutionaries do what follows from that fact.',
9:'If the manifesto is a promise, keep it. If it is a trick, understand that the audience can read.',
10:'Patriots who are licensed to hate will eventually require new enemies when the old ones are exhausted.',
11:'Every service can endure bad men. No service can indefinitely endure a system that promotes them.',
12:'The artillery will clear the street. It will not clear the memory of the street.',
13:'Ambiguity feels sovereign because it preserves every option. In practice it gives the next crisis the right to choose for you.',
14:'You do not need to love parliament. You need to decide whether you prefer opposition with minutes and rules.',
15:'Procedure is not weakness. Revenge dressed as procedure is.',
16:'Do not let the bomb write the reform program. Do not let it write the penal code either.',
17:'A peasant who owns land may still hate you. He will at least have something politics must explain before it burns.',
18:'A quieter chamber obtained by changing the electorate may cost more legitimacy than the noise ever did.',
19:'Use the tame Duma or one day a wild street will remind everyone what representation was supposed to absorb.',
20:'Rubles are not ideological. That is why they are so useful.',
21:'Land reform fails in cadastral offices long before it fails in speeches.',
22:'Twenty years requires more courage from the palace than one dramatic decree. Continuity has fewer trumpets.',
23:'An empire can contain difference. It cannot indefinitely contain the claim that difference is treason.',
24:'Never spend tomorrow’s strength merely to avoid admitting today’s weakness.',
25:'A promise to Serbia is also a promise to your future self under worse conditions.',
26:'Professional armies are politically boring. That is one of their greatest virtues.',
27:'If the Church is holy, permit it enough freedom to prove the state did not manufacture the holiness.',
28:'Oil does not stabilize a province merely because the refinery remains open.',
29:'Every forbidden language acquires a literature about being forbidden.',
30:'If every minister requires the Tsar to settle his quarrel, you have not centralized power. You have privatized paralysis.',
31:'Do not confuse a guaranteed Russian majority with a loyal western province.',
32:'The court is hiding a medical fact and creating a political mythology. Secrets do not remain empty; people furnish them.',
33:'If your servants learn that court intrigue can reverse public policy, they will stop negotiating with policy.',
34:'A police service that cannot distinguish agent from enemy is not omniscient. It is contaminated.',
35:'If the program survives him, Russia has learned something. If not, his enemies have inherited the state.',
36:'Prosperity gives you room. Do not mistake room for resolution.',
37:'Power exercised where resistance is weak is the purest evidence of what you think power is for.',
38:'Calm is useful. Worshipping calm is how unresolved problems become ancestral.',
39:'Dismiss the sentence “so it was, so it will be.” States die from phrases like that because they teach subjects that reform is fiction.',
40:'The public cannot be ordered to believe the court is innocent. Give it less to imagine.',
41:'You need not believe the prophet to consider whether his warning is strategically correct.',
42:'Clients are countries. The moment that irritates you is usually the moment they prove it.',
43:'If the plan eliminates political choice, the plan has become a constitution nobody voted on.',
44:'A holy objective still requires ordinary logistics and unholy diplomacy.',
45:'Three hundred years is long enough to know that survival and righteousness are not synonyms.',
46:'Let Orthodoxy be larger than the police regulations written in its defense.',
47:'When the state pays men to be near terror, it must ensure terror is not what keeps them employed.',
48:'Poland will remember itself whether you permit the memory or police it.',
49:'Brother peoples are still peoples. Family language does not abolish interests.',
50:'The factory has taught workers coordination. The question is whether the law teaches them citizenship before underground parties teach them war.',
51:'A cabinet capable of deciding without you is not necessarily a cabinet capable of betraying you.',
52:'The truth about Alexei is terrible. The stories created by secrecy may become politically worse.',
53:'Do not promise France an offensive merely because the railway map makes the promise look measurable.',
54:'Choose an alignment before crisis chooses one from your preparations.',
55:'This is the year to spend prestige preventing tests of prestige.',
56:'Punish the guilty if you can identify them. Do not let a murder appoint every foreign ministry in Europe as its accomplice.',
57:'If Berlin means to restrain Vienna, insist on a restraint that can be observed rather than a friendship that can be quoted.',
58:'Tell Serbia exactly what Russia will and will not die for.',
59:'The ultimatum is designed to make moderation look like cowardice. Refuse the design.',
60:'Use the Serbian reply while it is still a diplomatic weapon and not merely an exhibit in the archive of how peace failed.',
61:'The generals are correct that plans have costs. They are not entitled to decide that those costs are foreign policy.',
62:'Write to Willy, but make the ministries obey what the cousins agree.',
63:'Inventory reality. “Not mobilization” is not a military category.',
64:'One clear order is now worth more than five expressions of imperial will.',
65:'Certainty is contagious in frightened rooms. Do not mistake contagion for wisdom.',
66:'If you reverse, reverse once and own it. If you proceed, do not pretend the machine forced you.',
67:'A simultaneous step backward is still available. Pride is the remaining enemy with no army attached.',
68:'Tell the country what happened before the war teaches it what must have happened.',
69:'A humiliating peace is an argument. A glorious war is a cemetery that argues back.',
70:'At the end, Nicky, the question is not whether God will judge Europe. It is whether you will decide before everyone starts speaking for Him.'
};

const oatrBaseQuestionTextForTone = questionText;
questionText = function(q) {
  const copy = oatrBaseQuestionTextForTone(q);
  const fn = OATR_POLITICAL_CODA[q.id];
  if (!fn || !copy || !Array.isArray(copy.body)) return copy;
  const coda = fn(branchContext());
  if (!coda) return copy;
  return { ...copy, body: [...copy.body, `<span class="political-coda">${coda}</span>`] };
};

const oatrBaseConsequenceForTone = consequenceText;
consequenceText = function(effects, advisor) {
  const q = currentQuestion();
  const base = oatrBaseConsequenceForTone(effects, advisor);
  const coda = q ? OATR_ADVISOR_CODA[q.id] : null;
  return coda ? `${base} ${coda}` : base;
};

render();
